site_name: Py7za
nav:
  - Home: index.md
  - 'Getting Started': getting_started.md
  - 'Configuration and CLI': configuration.md
  - Gotchas: gotchas.md
  - About: about.md
theme: readthedocs
markdown_extensions:
  - admonition
